[package]
name = "fspiox-api"
version = "0.2.1"
authors = ["msk- <mattkingston@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
postgres-types = { version = "0.2", features = ["derive", "with-uuid-0_8", "with-chrono-0_4"] }
serde_json = "1"
serde = { version = "1", features = ["derive"] }
tokio-postgres = "0.7"
uuid = { version = "0.8", features = ["serde", "v4"] }
rust_decimal = { version = "1", features = ["db-postgres"] }
