/*
 * Open API for FSP Interoperability (FSPIOP)
 *
 * Based on API Definition.docx updated on 2020-05-19 Version 1.1. Note - The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * The version of the OpenAPI document: 1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// BulkQuotesPostRequest : POST /bulkQuotes object



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkQuotesPostRequest {
    /// Identifier that correlates all messages of the same sequence. The API data type UUID (Universally Unique Identifier) is a JSON String in canonical format, conforming to RFC 4122, that is restricted by a regular expression for interoperability reasons. An UUID is always 36 characters long, 32 hexadecimal symbols and 4 dashes (‘-‘).
    #[serde(rename = "bulkQuoteId")]
    pub bulk_quote_id: String,
    #[serde(rename = "payer")]
    pub payer: crate::models::Party,
    #[serde(rename = "geoCode", skip_serializing_if = "Option::is_none")]
    pub geo_code: Option<crate::models::GeoCode>,
    /// The API data type DateTime is a JSON String in a lexical format that is restricted by a regular expression for interoperability reasons. The format is according to ISO 8601, expressed in a combined date, time and time zone format. A more readable version of the format is yyyy-MM-ddTHH:mm:ss.SSS[-HH:MM]. Examples -  \"2016-05-24T08:38:08.699-04:00\", \"2016-05-24T08:38:08.699Z\" (where Z indicates Zulu time zone, same as UTC).
    #[serde(rename = "expiration", skip_serializing_if = "Option::is_none")]
    pub expiration: Option<String>,
    /// List of quotes elements.
    #[serde(rename = "individualQuotes")]
    pub individual_quotes: Vec<crate::models::IndividualQuote>,
    #[serde(rename = "extensionList", skip_serializing_if = "Option::is_none")]
    pub extension_list: Option<crate::models::ExtensionList>,
}

impl BulkQuotesPostRequest {
    /// POST /bulkQuotes object
    pub fn new(bulk_quote_id: String, payer: crate::models::Party, individual_quotes: Vec<crate::models::IndividualQuote>) -> BulkQuotesPostRequest {
        BulkQuotesPostRequest {
            bulk_quote_id,
            payer,
            geo_code: None,
            expiration: None,
            individual_quotes,
            extension_list: None,
        }
    }
}


