/*
 * Open API for FSP Interoperability (FSPIOP)
 *
 * Based on API Definition.docx updated on 2020-05-19 Version 1.1. Note - The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * The version of the OpenAPI document: 1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// BulkTransfersPostRequest : POST /bulkTransfers object



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkTransfersPostRequest {
    /// Identifier that correlates all messages of the same sequence. The API data type UUID (Universally Unique Identifier) is a JSON String in canonical format, conforming to RFC 4122, that is restricted by a regular expression for interoperability reasons. An UUID is always 36 characters long, 32 hexadecimal symbols and 4 dashes (‘-‘).
    #[serde(rename = "bulkTransferId")]
    pub bulk_transfer_id: String,
    /// Identifier that correlates all messages of the same sequence. The API data type UUID (Universally Unique Identifier) is a JSON String in canonical format, conforming to RFC 4122, that is restricted by a regular expression for interoperability reasons. An UUID is always 36 characters long, 32 hexadecimal symbols and 4 dashes (‘-‘).
    #[serde(rename = "bulkQuoteId")]
    pub bulk_quote_id: String,
    /// FSP identifier.
    #[serde(rename = "payerFsp")]
    pub payer_fsp: String,
    /// FSP identifier.
    #[serde(rename = "payeeFsp")]
    pub payee_fsp: String,
    /// List of IndividualTransfer elements.
    #[serde(rename = "individualTransfers")]
    pub individual_transfers: Vec<crate::models::IndividualTransfer>,
    /// The API data type DateTime is a JSON String in a lexical format that is restricted by a regular expression for interoperability reasons. The format is according to ISO 8601, expressed in a combined date, time and time zone format. A more readable version of the format is yyyy-MM-ddTHH:mm:ss.SSS[-HH:MM]. Examples -  \"2016-05-24T08:38:08.699-04:00\", \"2016-05-24T08:38:08.699Z\" (where Z indicates Zulu time zone, same as UTC).
    #[serde(rename = "expiration")]
    pub expiration: String,
    #[serde(rename = "extensionList", skip_serializing_if = "Option::is_none")]
    pub extension_list: Option<crate::models::ExtensionList>,
}

impl BulkTransfersPostRequest {
    /// POST /bulkTransfers object
    pub fn new(bulk_transfer_id: String, bulk_quote_id: String, payer_fsp: String, payee_fsp: String, individual_transfers: Vec<crate::models::IndividualTransfer>, expiration: String) -> BulkTransfersPostRequest {
        BulkTransfersPostRequest {
            bulk_transfer_id,
            bulk_quote_id,
            payer_fsp,
            payee_fsp,
            individual_transfers,
            expiration,
            extension_list: None,
        }
    }
}


