/* 
 * Open API for FSP Interoperability (FSPIOP)
 *
 * Based on API Definition.docx updated on 2020-05-19 Version 1.1. Note - The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// Currency : The currency codes defined in ISO 4217 as three-letter alphabetic codes are used as the standard naming representation for currencies.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Currency {
}

impl Currency {
  /// The currency codes defined in ISO 4217 as three-letter alphabetic codes are used as the standard naming representation for currencies.
  pub fn new() -> Currency {
    Currency {
    }
  }

}

// TODO enum 
// List of Currency
//const (
//  
//  
//  
//)


