/*
 * Open API for FSP Interoperability (FSPIOP)
 *
 * Based on API Definition.docx updated on 2020-05-19 Version 1.1. Note - The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * The version of the OpenAPI document: 1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ErrorInformationObject : Data model for the complex type object that contains ErrorInformation.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorInformationObject {
    #[serde(rename = "errorInformation")]
    pub error_information: crate::models::ErrorInformation,
}

impl ErrorInformationObject {
    /// Data model for the complex type object that contains ErrorInformation.
    pub fn new(error_information: crate::models::ErrorInformation) -> ErrorInformationObject {
        ErrorInformationObject {
            error_information,
        }
    }
}


