/* 
 * Open API for FSP Interoperability (FSPIOP)
 *
 * Based on API Definition.docx updated on 2020-05-19 Version 1.1. Note - The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ErrorInformationResponse : Data model for the complex type object that contains an optional element ErrorInformation used along with 4xx and 5xx responses.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ErrorInformationResponse {
  #[serde(rename = "errorInformation")]
  error_information: Option<::models::ErrorInformation>
}

impl ErrorInformationResponse {
  /// Data model for the complex type object that contains an optional element ErrorInformation used along with 4xx and 5xx responses.
  pub fn new() -> ErrorInformationResponse {
    ErrorInformationResponse {
      error_information: None
    }
  }

  pub fn set_error_information(&mut self, error_information: ::models::ErrorInformation) {
    self.error_information = Some(error_information);
  }

  pub fn with_error_information(mut self, error_information: ::models::ErrorInformation) -> ErrorInformationResponse {
    self.error_information = Some(error_information);
    self
  }

  pub fn error_information(&self) -> Option<&::models::ErrorInformation> {
    self.error_information.as_ref()
  }

  pub fn reset_error_information(&mut self) {
    self.error_information = None;
  }

}



