/* 
 * Open API for FSP Interoperability (FSPIOP)
 *
 * Based on API Definition.docx updated on 2020-05-19 Version 1.1. Note - The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ErrorInformationObject : Data model for the complex type object that contains ErrorInformation.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ErrorInformationObject {
  #[serde(rename = "errorInformation")]
  error_information: ::models::ErrorInformation
}

impl ErrorInformationObject {
  /// Data model for the complex type object that contains ErrorInformation.
  pub fn new(error_information: ::models::ErrorInformation) -> ErrorInformationObject {
    ErrorInformationObject {
      error_information: error_information
    }
  }

  pub fn set_error_information(&mut self, error_information: ::models::ErrorInformation) {
    self.error_information = error_information;
  }

  pub fn with_error_information(mut self, error_information: ::models::ErrorInformation) -> ErrorInformationObject {
    self.error_information = error_information;
    self
  }

  pub fn error_information(&self) -> &::models::ErrorInformation {
    &self.error_information
  }


}



