/*
 * Open API for FSP Interoperability (FSPIOP)
 *
 * Based on API Definition.docx updated on 2020-05-19 Version 1.1. Note - The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * The version of the OpenAPI document: 1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ErrorInformationResponse : Data model for the complex type object that contains an optional element ErrorInformation used along with 4xx and 5xx responses.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorInformationResponse {
    #[serde(rename = "errorInformation", skip_serializing_if = "Option::is_none")]
    pub error_information: Option<crate::models::ErrorInformation>,
}

impl ErrorInformationResponse {
    /// Data model for the complex type object that contains an optional element ErrorInformation used along with 4xx and 5xx responses.
    pub fn new() -> ErrorInformationResponse {
        ErrorInformationResponse {
            error_information: None,
        }
    }
}


