/*
 * Open API for FSP Interoperability (FSPIOP)
 *
 * Based on API Definition.docx updated on 2020-05-19 Version 1.1. Note - The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * The version of the OpenAPI document: 1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ExtensionList : Data model for the complex type ExtensionList



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExtensionList {
    /// Number of Extension elements
    #[serde(rename = "extension")]
    pub extension: Vec<crate::models::Extension>,
}

impl ExtensionList {
    /// Data model for the complex type ExtensionList
    pub fn new(extension: Vec<crate::models::Extension>) -> ExtensionList {
        ExtensionList {
            extension,
        }
    }
}


