/*
 * Open API for FSP Interoperability (FSPIOP)
 *
 * Based on API Definition.docx updated on 2020-05-19 Version 1.1. Note - The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * The version of the OpenAPI document: 1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Extension : Data model for the complex type Extension



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Extension {
    /// Extension key.
    #[serde(rename = "key")]
    pub key: String,
    /// Extension value.
    #[serde(rename = "value")]
    pub value: String,
}

impl Extension {
    /// Data model for the complex type Extension
    pub fn new(key: String, value: String) -> Extension {
        Extension {
            key,
            value,
        }
    }
}


