/*
 * Open API for FSP Interoperability (FSPIOP)
 *
 * Based on API Definition.docx updated on 2020-05-19 Version 1.1. Note - The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * The version of the OpenAPI document: 1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GeoCode : Data model for the complex type GeoCode. Indicates the geographic location from where the transaction was initiated.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GeoCode {
    /// The API data type Latitude is a JSON String in a lexical format that is restricted by a regular expression for interoperability reasons.
    #[serde(rename = "latitude")]
    pub latitude: String,
    /// The API data type Longitude is a JSON String in a lexical format that is restricted by a regular expression for interoperability reasons.
    #[serde(rename = "longitude")]
    pub longitude: String,
}

impl GeoCode {
    /// Data model for the complex type GeoCode. Indicates the geographic location from where the transaction was initiated.
    pub fn new(latitude: String, longitude: String) -> GeoCode {
        GeoCode {
            latitude,
            longitude,
        }
    }
}


