/* 
 * Open API for FSP Interoperability (FSPIOP)
 *
 * Based on API Definition.docx updated on 2020-05-19 Version 1.1. Note - The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// Latitude : The API data type Latitude is a JSON String in a lexical format that is restricted by a regular expression for interoperability reasons.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Latitude {
}

impl Latitude {
  /// The API data type Latitude is a JSON String in a lexical format that is restricted by a regular expression for interoperability reasons.
  pub fn new() -> Latitude {
    Latitude {
    }
  }

}



