/*
 * Open API for FSP Interoperability (FSPIOP)
 *
 * Based on API Definition.docx updated on 2020-05-19 Version 1.1. Note - The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * The version of the OpenAPI document: 1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ParticipantsTypeIdPutResponse : PUT /participants/{Type}/{ID}/{SubId}, /participants/{Type}/{ID} object



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ParticipantsTypeIdPutResponse {
    /// FSP identifier.
    #[serde(rename = "fspId", skip_serializing_if = "Option::is_none")]
    pub fsp_id: Option<String>,
}

impl ParticipantsTypeIdPutResponse {
    /// PUT /participants/{Type}/{ID}/{SubId}, /participants/{Type}/{ID} object
    pub fn new() -> ParticipantsTypeIdPutResponse {
        ParticipantsTypeIdPutResponse {
            fsp_id: None,
        }
    }
}


