/*
 * Open API for FSP Interoperability (FSPIOP)
 *
 * Based on API Definition.docx updated on 2020-05-19 Version 1.1. Note - The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * The version of the OpenAPI document: 1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ParticipantsIdPutResponse : PUT /participants/{ID} object



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ParticipantsIdPutResponse {
    /// List of PartyResult elements that were either created or failed to be created.
    #[serde(rename = "partyList")]
    pub party_list: Vec<crate::models::PartyResult>,
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<crate::models::Currency>,
}

impl ParticipantsIdPutResponse {
    /// PUT /participants/{ID} object
    pub fn new(party_list: Vec<crate::models::PartyResult>) -> ParticipantsIdPutResponse {
        ParticipantsIdPutResponse {
            party_list,
            currency: None,
        }
    }
}


