/*
 * Open API for FSP Interoperability (FSPIOP)
 *
 * Based on API Definition.docx updated on 2020-05-19 Version 1.1. Note - The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * The version of the OpenAPI document: 1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ParticipantsTypeIdSubIdPostRequest : POST /participants/{Type}/{ID}/{SubId}, /participants/{Type}/{ID} object



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ParticipantsTypeIdSubIdPostRequest {
    /// FSP identifier.
    #[serde(rename = "fspId")]
    pub fsp_id: String,
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<crate::models::Currency>,
    #[serde(rename = "extensionList", skip_serializing_if = "Option::is_none")]
    pub extension_list: Option<crate::models::ExtensionList>,
}

impl ParticipantsTypeIdSubIdPostRequest {
    /// POST /participants/{Type}/{ID}/{SubId}, /participants/{Type}/{ID} object
    pub fn new(fsp_id: String) -> ParticipantsTypeIdSubIdPostRequest {
        ParticipantsTypeIdSubIdPostRequest {
            fsp_id,
            currency: None,
            extension_list: None,
        }
    }
}


