/* 
 * Open API for FSP Interoperability (FSPIOP)
 *
 * Based on API Definition.docx updated on 2020-05-19 Version 1.1. Note - The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// PartiesTypeIdPutResponse : PUT /parties/{Type}/{ID} object

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct PartiesTypeIdPutResponse {
  /// Information regarding the requested Party.
  #[serde(rename = "party")]
  party: ::models::Party
}

impl PartiesTypeIdPutResponse {
  /// PUT /parties/{Type}/{ID} object
  pub fn new(party: ::models::Party) -> PartiesTypeIdPutResponse {
    PartiesTypeIdPutResponse {
      party: party
    }
  }

  pub fn set_party(&mut self, party: ::models::Party) {
    self.party = party;
  }

  pub fn with_party(mut self, party: ::models::Party) -> PartiesTypeIdPutResponse {
    self.party = party;
    self
  }

  pub fn party(&self) -> &::models::Party {
    &self.party
  }


}



