/*
 * Open API for FSP Interoperability (FSPIOP)
 *
 * Based on API Definition.docx updated on 2020-05-19 Version 1.1. Note - The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * The version of the OpenAPI document: 1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PartiesTypeIdPutResponse : PUT /parties/{Type}/{ID} object



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartiesTypeIdPutResponse {
    #[serde(rename = "party")]
    pub party: crate::models::Party,
}

impl PartiesTypeIdPutResponse {
    /// PUT /parties/{Type}/{ID} object
    pub fn new(party: crate::models::Party) -> PartiesTypeIdPutResponse {
        PartiesTypeIdPutResponse {
            party,
        }
    }
}


