/*
 * Open API for FSP Interoperability (FSPIOP)
 *
 * Based on API Definition.docx updated on 2020-05-19 Version 1.1. Note - The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * The version of the OpenAPI document: 1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PersonalIdentifierType : Below are the allowed values for the enumeration - PASSPORT A passport number is used as reference to a Party. - NATIONAL_REGISTRATION A national registration number is used as reference to a Party. - DRIVING_LICENSE A driving license is used as reference to a Party. - ALIEN_REGISTRATION An alien registration number is used as reference to a Party. - NATIONAL_ID_CARD A national ID card number is used as reference to a Party. - EMPLOYER_ID A tax identification number is used as reference to a Party. - TAX_ID_NUMBER A tax identification number is used as reference to a Party. - SENIOR_CITIZENS_CARD A senior citizens card number is used as reference to a Party. - MARRIAGE_CERTIFICATE A marriage certificate number is used as reference to a Party. - HEALTH_CARD A health card number is used as reference to a Party. - VOTERS_ID A voter’s identification number is used as reference to a Party. - UNITED_NATIONS An UN (United Nations) number is used as reference to a Party. - OTHER_ID Any other type of identification type number is used as reference to a Party.

/// Below are the allowed values for the enumeration - PASSPORT A passport number is used as reference to a Party. - NATIONAL_REGISTRATION A national registration number is used as reference to a Party. - DRIVING_LICENSE A driving license is used as reference to a Party. - ALIEN_REGISTRATION An alien registration number is used as reference to a Party. - NATIONAL_ID_CARD A national ID card number is used as reference to a Party. - EMPLOYER_ID A tax identification number is used as reference to a Party. - TAX_ID_NUMBER A tax identification number is used as reference to a Party. - SENIOR_CITIZENS_CARD A senior citizens card number is used as reference to a Party. - MARRIAGE_CERTIFICATE A marriage certificate number is used as reference to a Party. - HEALTH_CARD A health card number is used as reference to a Party. - VOTERS_ID A voter’s identification number is used as reference to a Party. - UNITED_NATIONS An UN (United Nations) number is used as reference to a Party. - OTHER_ID Any other type of identification type number is used as reference to a Party.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PersonalIdentifierType {
    #[serde(rename = "PASSPORT")]
    PASSPORT,
    #[serde(rename = "NATIONAL_REGISTRATION")]
    NATIONALREGISTRATION,
    #[serde(rename = "DRIVING_LICENSE")]
    DRIVINGLICENSE,
    #[serde(rename = "ALIEN_REGISTRATION")]
    ALIENREGISTRATION,
    #[serde(rename = "NATIONAL_ID_CARD")]
    NATIONALIDCARD,
    #[serde(rename = "EMPLOYER_ID")]
    EMPLOYERID,
    #[serde(rename = "TAX_ID_NUMBER")]
    TAXIDNUMBER,
    #[serde(rename = "SENIOR_CITIZENS_CARD")]
    SENIORCITIZENSCARD,
    #[serde(rename = "MARRIAGE_CERTIFICATE")]
    MARRIAGECERTIFICATE,
    #[serde(rename = "HEALTH_CARD")]
    HEALTHCARD,
    #[serde(rename = "VOTERS_ID")]
    VOTERSID,
    #[serde(rename = "UNITED_NATIONS")]
    UNITEDNATIONS,
    #[serde(rename = "OTHER_ID")]
    OTHERID,

}




