/* 
 * Open API for FSP Interoperability (FSPIOP)
 *
 * Based on API Definition.docx updated on 2020-05-19 Version 1.1. Note - The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// TransfersIdPutResponse : PUT /transfers/{ID} object

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct TransfersIdPutResponse {
  /// Fulfilment of the condition specified with the transaction. Mandatory if transfer has completed successfully.
  #[serde(rename = "fulfilment")]
  fulfilment: Option<::models::IlpFulfilment>,
  /// Time and date when the transaction was completed.
  #[serde(rename = "completedTimestamp")]
  completed_timestamp: Option<String>,
  /// State of the transfer.
  #[serde(rename = "transferState")]
  transfer_state: ::models::TransferState,
  /// Optional extension, specific to deployment.
  #[serde(rename = "extensionList")]
  extension_list: Option<::models::ExtensionList>
}

impl TransfersIdPutResponse {
  /// PUT /transfers/{ID} object
  pub fn new(transfer_state: ::models::TransferState) -> TransfersIdPutResponse {
    TransfersIdPutResponse {
      fulfilment: None,
      completed_timestamp: None,
      transfer_state: transfer_state,
      extension_list: None
    }
  }

  pub fn set_fulfilment(&mut self, fulfilment: ::models::IlpFulfilment) {
    self.fulfilment = Some(fulfilment);
  }

  pub fn with_fulfilment(mut self, fulfilment: ::models::IlpFulfilment) -> TransfersIdPutResponse {
    self.fulfilment = Some(fulfilment);
    self
  }

  pub fn fulfilment(&self) -> Option<&::models::IlpFulfilment> {
    self.fulfilment.as_ref()
  }

  pub fn reset_fulfilment(&mut self) {
    self.fulfilment = None;
  }

  pub fn set_completed_timestamp(&mut self, completed_timestamp: String) {
    self.completed_timestamp = Some(completed_timestamp);
  }

  pub fn with_completed_timestamp(mut self, completed_timestamp: String) -> TransfersIdPutResponse {
    self.completed_timestamp = Some(completed_timestamp);
    self
  }

  pub fn completed_timestamp(&self) -> Option<&String> {
    self.completed_timestamp.as_ref()
  }

  pub fn reset_completed_timestamp(&mut self) {
    self.completed_timestamp = None;
  }

  pub fn set_transfer_state(&mut self, transfer_state: ::models::TransferState) {
    self.transfer_state = transfer_state;
  }

  pub fn with_transfer_state(mut self, transfer_state: ::models::TransferState) -> TransfersIdPutResponse {
    self.transfer_state = transfer_state;
    self
  }

  pub fn transfer_state(&self) -> &::models::TransferState {
    &self.transfer_state
  }


  pub fn set_extension_list(&mut self, extension_list: ::models::ExtensionList) {
    self.extension_list = Some(extension_list);
  }

  pub fn with_extension_list(mut self, extension_list: ::models::ExtensionList) -> TransfersIdPutResponse {
    self.extension_list = Some(extension_list);
    self
  }

  pub fn extension_list(&self) -> Option<&::models::ExtensionList> {
    self.extension_list.as_ref()
  }

  pub fn reset_extension_list(&mut self) {
    self.extension_list = None;
  }

}



