/*
 * Open API for FSP Interoperability (FSPIOP)
 *
 * Based on API Definition.docx updated on 2020-05-19 Version 1.1. Note - The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * The version of the OpenAPI document: 1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TransfersPostRequest : POST /transfers Request object



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransfersPostRequest {
    /// Identifier that correlates all messages of the same sequence. The API data type UUID (Universally Unique Identifier) is a JSON String in canonical format, conforming to RFC 4122, that is restricted by a regular expression for interoperability reasons. An UUID is always 36 characters long, 32 hexadecimal symbols and 4 dashes (‘-‘).
    #[serde(rename = "transferId")]
    pub transfer_id: String,
    /// FSP identifier.
    #[serde(rename = "payeeFsp")]
    pub payee_fsp: String,
    /// FSP identifier.
    #[serde(rename = "payerFsp")]
    pub payer_fsp: String,
    #[serde(rename = "amount")]
    pub amount: crate::models::Money,
    /// Information for recipient (transport layer information).
    #[serde(rename = "ilpPacket")]
    pub ilp_packet: String,
    /// Condition that must be attached to the transfer by the Payer.
    #[serde(rename = "condition")]
    pub condition: String,
    /// The API data type DateTime is a JSON String in a lexical format that is restricted by a regular expression for interoperability reasons. The format is according to ISO 8601, expressed in a combined date, time and time zone format. A more readable version of the format is yyyy-MM-ddTHH:mm:ss.SSS[-HH:MM]. Examples -  \"2016-05-24T08:38:08.699-04:00\", \"2016-05-24T08:38:08.699Z\" (where Z indicates Zulu time zone, same as UTC).
    #[serde(rename = "expiration")]
    pub expiration: String,
    #[serde(rename = "extensionList", skip_serializing_if = "Option::is_none")]
    pub extension_list: Option<crate::models::ExtensionList>,
}

impl TransfersPostRequest {
    /// POST /transfers Request object
    pub fn new(transfer_id: String, payee_fsp: String, payer_fsp: String, amount: crate::models::Money, ilp_packet: String, condition: String, expiration: String) -> TransfersPostRequest {
        TransfersPostRequest {
            transfer_id,
            payee_fsp,
            payer_fsp,
            amount,
            ilp_packet,
            condition,
            expiration,
            extension_list: None,
        }
    }
}


